-- ============================================================================
-- 0004 — DEPRECATED, do not run this file.
--
-- This used to seed demo writers + articles via raw INSERTs into auth.users.
-- That approach is fragile: Supabase's internal auth schema has required
-- columns that differ across project versions, so it can fail silently
-- depending on when your project was created — which is very likely why
-- the seed articles never showed up.
--
-- Use scripts/seed-articles.mjs instead (see the README's "Seed content"
-- section). It uses Supabase's official Admin API, so it works the same
-- way regardless of your project's schema version.
-- ============================================================================
